---
output: html_document
---


```{r}
library(magrittr)
```

```{r}
a <- "C:/Users/chase/Documents/old_dplyr"
b <- "C:/Users/chase/Documents/new_dplyr"
```


```{r eval = FALSE, include = TRUE}

devtools::install_github("tidyverse/dplyr@v0.7.4.9005", 
                         lib = a, 
                         force = T)


devtools::install_github("tidyverse/dplyr@f0993bb", 
                         lib = b, 
                         force = T)

```



New first:

```{r}
library("dplyr",
        lib.loc = b,
        warn.conflicts = FALSE)

sessionInfo()$otherPkgs$dplyr$Version

```


```{r}

z1 <- tibble(
  x = 1:3, 
  f = factor(c("Animal_1", "Animal_2", "Animal_2"), levels = c("Animal_1", "Animal_2", "Animal_3"))
)

z2 <- group_by(z1, f)

z3 <- dplyr::summarise(z2, count_animals = dplyr::n() )
z3
```

```{r}
z4 <- z3$count_animals
try(names(z4) <- levels(z1$f))
z4
```



```{r}

detach("package:dplyr", unload=TRUE)

```


Old second

```{r}
library("dplyr",
        lib.loc = a,
        warn.conflicts = FALSE)

sessionInfo()$otherPkgs$dplyr$Version

```

```{r}

z1 <- tibble(
  x = 1:3, 
  f = factor(c("Animal_1", "Animal_2", "Animal_2"), levels = c("Animal_1", "Animal_2", "Animal_3"))
)

z2 <- group_by(z1, f)

z3 <- dplyr::summarise(z2, count_animals = dplyr::n() )
z3
```

```{r}
z4 <- z3$count_animals
try(names(z4) <- levels(z1$f))
z4
```
